### PR TITLE
Update use-node-public-ips.md

### PR DESCRIPTION
**Pull request by ffidelis**
Fixed the required versions 1.24->1.29
Fixed the _azurecli-interactive_ fields without the command line
Fixed some discrepancies in the name patterns
Fixed the parameter `node-public-ip-prefix` -> `--node-public-ip-prefix-id`

### CODE REVIEW

**Comment by ffidelis** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by ShannonLeavitt** [comment]
@phealy

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by reknai** [comment]
@phealy : Can you please review this PR.

**Review by schaffererin — APPROVED** [review]

**Comment by schaffererin** [comment]
#sign-off

**Comment by schaffererin** [comment]
@ShannonLeavitt, this is good for merging :)

**Pull request merged**
