### PR TITLE
docs: fix keda links 

### PR DESCRIPTION
**Pull request by KaranbirSingh7**
### Changelog

- small fix to point docs to keda-overview page

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Nickomang 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
#assign-reviewer:schaffererin

**Review by schaffererin — APPROVED** [review]

**Comment by schaffererin** [comment]
#sign-off

**Comment by schaffererin** [comment]
Hi, @Jak-MS, this is good for sign off!

**Comment by Jak-MS** [comment]
taking approval from @schaffererin as sign off.

**Pull request merged**
