### PR TITLE
Update use-metrics-server-vertical-pod-autoscaler.md

### PR DESCRIPTION
**Pull request by reknai**
PR for https://supportability.visualstudio.com/AzureContainers/_workitems/edit/81126

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Nickomang 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by reknai** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@Nickomang - nudge. can you take a look? thanks.

**Comment by Nickomang** [comment]
#sign-off

**Pull request merged**
